#! /bin/sh
#
# mumble server initscript for mandriva
#
### BEGIN INIT INFO
# Provides:             mumble-server
# Required-Start:       $network $local_fs $remote_fs messagebus
# Required-Stop:	$network $local_fs $remote_fs messagebus
# Should-Start:		$mysql
# Should-Stop:		$mysql
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Mumble VoIP Server
# Description:		Mumble VoIP Server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=mumble-server
LOCK_FILE=/var/lock/subsys/$NAME
PID_FILE=/var/run/$NAME/$NAME.pid
DAEMON=/usr/sbin/murmurd
USER=mumble-server

test -x $DAEMON || exit 0

INIFILE=/etc/mumble-server.ini
DAEMON_OPTS="-ini $INIFILE"

start() {
  	printf "Starting $NAME: "
	daemon --user $USER $DAEMON $DAEMON_OPTS
	RETVAL=$?
    	echo
    	[ $RETVAL -eq 0 ] && touch $LOCK_FILE
}

stop()  {
  	printf "Shutting down $NAME: "
	killproc $DAEMON
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ]; then
		rm -f $LOCK_FILE
		rm -f $PID_FILE
	fi
}


reload() {
	printf "Reloading $NAME configuration: "
	killproc $DAEMON -HUP
	RETVAL=$?
	echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $DAEMON
        RETVAL=$?
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if [ -f $LOCK_FILE ]; then
            stop
            start
        fi
        ;;
    *)
        printf "Usage: %s {start|stop|restart|reload|condrestart|status}\n" "$0"
esac

exit $RETVAL
